### ISSUE TITLE
select tag's text is getting cut off by padding

### ISSUE THREAD

**Issue by chef-danny-d** [12px/morr#1]
The drop-down text is getting cut off by the padding. Add the following line to your styles to fix it. 
```css
select{
    padding: 0 1rem;
}
```

https://github.com/12px/morr/blob/fac33b23d305a221ca8e520ea3a5531b3dfd5032/dist/morr.css#L550-L566
